export const DUMMY_DATA = [
  {
    dishName: "Fried Rice",
    type: "Chinese cuisine",
    photoURL: "https://houseofnasheats.com/wp-content/uploads/2023/01/Chicken-Fried-Rice-Recipe-12-scaled.jpg",
    id: 1,
    tags: ["Chinese", "High-protein"],
    ingredients: [
      "2 cups cooked rice",
      "1 cup diced chicken",
      "1 cup mixed vegetables (peas, carrots, corn)",
      "3 eggs, beaten",
      "4 tablespoons soy sauce",
      "1 tablespoon oil",
      "Salt and pepper to taste",
    ],
    recipeInstructions: [
      "Heat oil in a pan over medium heat.",
      "Add diced chicken and cook until browned.",
      "Push chicken to one side, add beaten eggs to the other side, and scramble.",
      "Add mixed vegetables and stir-fry for a few minutes.",
      "Add cooked rice and soy sauce, mix well.",
      "Season with salt and pepper to taste.",
      "Serve hot.",
    ],
  },
  {
    dishName: "Pesto Pasta",
    type: "Italian cuisine",
    photoURL: "https://www.cookingclassy.com/wp-content/uploads/2022/02/pesto-pasta-1.jpg",
    id: 2,
    tags: ["Vegetarian", "Italian"],
    ingredients: [
      "8 oz pasta",
      "1 cup fresh basil leaves",
      "1/2 cup grated Parmesan cheese",
      "1/2 cup pine nuts",
      "2 cloves garlic",
      "1/2 cup extra-virgin olive oil",
      "Salt and pepper to taste",
    ],
    recipeInstructions: [
      "Cook pasta according to package instructions.",
      "In a food processor, combine basil, Parmesan, pine nuts, and garlic. Pulse until finely chopped.",
      "With the processor running, slowly add olive oil until smooth.",
      "Season with salt and pepper to taste.",
      "Toss cooked pasta with pesto sauce and serve.",
    ],
  },
  {
    dishName: "Shrimp Curry",
    type: "Indonesian cuisine",
    photoURL: "https://dishingouthealth.com/wp-content/uploads/2022/08/CoconutShrimpSkillet_Styled1.jpg",
    id: 3,
    tags: ["Indonesian", "High-protein"],
    ingredients: [
      "1 lb shrimp, peeled and deveined",
      "1 can coconut milk",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 tablespoons red curry paste",
      "1 tablespoon fish sauce",
      "1 tablespoon brown sugar",
      "Fresh cilantro for garnish",
    ],
    recipeInstructions: [
      "In a pan, saute chopped onion until softened.",
      "Add red curry paste and cook for 1-2 minutes.",
      "Add shrimp and cook until pink and opaque.",
      "Stir in coconut milk, chopped tomatoes, fish sauce, and brown sugar. Simmer for 5-7 minutes.",
      "Garnish with fresh cilantro and serve over rice.",
    ],
  },
  {
        dishName: "Cheeseburger",
        type: "American cuisine",
        photoURL: "https://peppersandpennies.com/wp-content/uploads/2017/08/PP-20170814-3.jpg",
        id: 4,
        tags: ["American", "High-protein"],
        ingredients: [
            "1/2 pound medium ground beef",
            "1/2 pound ground pork",
            "1/2 sleeve of saltine crackers, finely crushed",
            "1/4 cup yellow onions, finely diced",
            "1 clove garlic, crushed",
            "1 tablespoon black pepper",
            "1 teaspoon salt",
            "1 teaspoon Worcestershire sauce",
            "1 large egg",
            "Buns and topping desired",
        ],
        recipeInstructions: [
            "Cook on grill or pan to medium-high.",
            "Mix all ingredients in large mixing bowl.",
            "Divide meat mixture into 4 equal sized balls",
            "Press down to create burger patties of equal width",
            "Grill or cook burgers at 160F, flipping only once.",
            "Remove from heat and let rest as you prepare the buns",
        ],
    },
    {
        dishName: "Reuben Sandwich",
        type: "American cuisine",
        photoURL: "https://www.allrecipes.com/thmb/4NsIWzNOAdTd69ADBr6UFt6W-c8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/47717-reuben-sandwich-ii-mike-phillips-b77c676e6aaf45e280d34e0c668d8f2f.jpeg",
        id: 5,
        tags: ["American", "Kosher", "< 1 hour"],
        ingredients: [
            "2 slices of rye bread",
            "1/2 cup Thousand Island dressing",
            "2 slices Swiss chesse",
            "2 slices deli slices corned beef",
            "1 cup sauerkraut, drained",
            "2 tablespoons butter, softened"
        ],
        recipeInstructions: [
            "Spread the dressing on one side of each slice of bread.",
            "Assemble the sandwiches. Butter the top of each sandwich.",
            "Place the sandwich butter-side down on the hot skillet or griddle.",
            "Butter the other side. Flip when the bottom slice is golden brown.",
            "Grill until both sides are golden brown.",
        ],
    },
    {
        dishName: "Hotdog",
        type: "American cuisine",
        photoURL: "https://media.cnn.com/api/v1/images/stellar/prod/170203114440-hot-dog.jpg",
        id: 6,
        tags: ["American", "Kosher", "Budget-friendly"],
        ingredients: [
            "1 hotdog",
            "1 hotdog bun",
            "Topping of choice",
        ],
        recipeInstructions: [
            "Bring a pot of water to a simmer.",
            "Add hotdog and simmer for 5 minutes",
            "Prepare the buns to liking",
            "Place hotdog in bun.",
            "Add toppings to liking"
        ],
    },
    {
        dishName: "Bibimbap",
        type: "Korean cuisine",
        photoURL: "https://recipetineats.com/wp-content/uploads/2019/05/Bibimbap_3.jpg",
        id: 7,
        tags: ["Korean", "High-protein"],
        ingredients: [
           "Cooked short-grain white rice",
           "1 cup julienned carrots" ,
           "1 cup bean sprouts",
           "1/2 pound beef",
           "2 tablespoons soy sauce",
           "1 clove garlic, minced",
           "2 tablespoons gochujang",
           "1 fried egg",
           "Sesame seeds",
        ],
        recipeInstructions: [
            "Saute carrots, spinach and zucchini.",
            "Cook beef with soy sauce and minced garlic",
            "Mix together gochujang and soy sauce",
            "Arrange rice, vegetables, and meat in a bowl",
            "Top bowl with fried egg",
            "Drizzle the gochujang sauce on top",
            "Sprinkle sesames seeds over the bibimbap",
            "Mix everything together.",
        ],
    },
    {
      dishName: "Vegetable Stir Fry",
      type: "Chinese cuisine",
      photoURL: "https://www.noracooks.com/wp-content/uploads/2022/04/frozen-vegetable-stir-fry-4.jpg",
      id: 8,
      tags: ["Vegetarian", "Chinese", "< 30 min"],
      ingredients: [
        "2 cups mixed vegetables (broccoli, bell peppers, snap peas)",
        "1 cup tofu, cubed",
        "3 tablespoons soy sauce",
        "2 tablespoons vegetable oil",
        "1 tablespoon ginger, minced",
        "1 clove garlic, minced",
        "Salt and pepper to taste",
      ],
      recipeInstructions: [
        "Heat oil in a wok or pan over high heat.",
        "Add tofu and stir-fry until golden.",
        "Add ginger and garlic, stir briefly.",
        "Add mixed vegetables and soy sauce, stir-fry until vegetables are tender-crisp.",
        "Season with salt and pepper to taste.",
        "Serve hot over rice.",
      ],
    },
    {
      dishName: "Mango Salsa",
      type: "Mexican cuisine",
      photoURL: "https://www.allrecipes.com/thmb/Uck7KwhB21janrR3nxo33exSeG0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/48032-mango-salsa-DDMFS-4x3-9a85c88aa4784139bfed9c7119d6b278.jpg",
      id: 9,
      tags: ["Mexican", "Low-carb", "< 30 min"],
      ingredients: [
        "2 ripe mangoes, diced",
        "1 red onion, finely chopped",
        "1 red bell pepper, diced",
        "1 jalapeño, seeded and minced",
        "1/4 cup fresh cilantro, chopped",
        "Juice of 2 limes",
        "Salt to taste",
      ],
      recipeInstructions: [
        "In a bowl, combine diced mangoes, red onion, red bell pepper, and jalapeño.",
        "Add fresh cilantro and lime juice, toss gently to combine.",
        "Season with salt to taste.",
        "Chill in the refrigerator for 15 minutes before serving.",
        "Serve as a refreshing salsa with tortilla chips or as a topping.",
      ],
    },
    {
      dishName: "Caprese Salad",
      type: "Mediterranean cuisine",
      photoURL: "https://www.allrecipes.com/thmb/heLutBLHDGeJOt_DPtl2gaSwWPg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/9369640-954a2499e7354f148c50388d5de0fb2e.jpg",
      id: 10,
      tags: ["Mediterranean", "Non-dairy"],
      ingredients: [
        "2 large tomatoes, sliced",
        "1 ball fresh mozzarella, sliced",
        "Fresh basil leaves",
        "2 tablespoons balsamic glaze",
        "Salt and pepper to taste",
      ],
      recipeInstructions: [
        "Arrange alternate slices of tomato and mozzarella on a serving platter.",
        "Tuck fresh basil leaves between the slices.",
        "Drizzle balsamic glaze over the salad.",
        "Season with salt and pepper to taste.",
        "Serve as a light and refreshing salad.",
      ],
    },
    {
      dishName: "Tofu Pad Thai",
      type: "Thai cuisine",
      photoURL: "https://www.allrecipes.com/thmb/11HVKKh8OrlLC3RlS3Ikh5dN_lo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/42968-pad-thai-DDMFS-4x3-f46b490ef89b4694b8bf4c5ac54a486b.jpg",
      id: 11,
      tags: ["Vegan", "High-protein", "Thai"],
      ingredients: [
        "8 oz rice noodles",
        "1 cup firm tofu, cubed",
        "2 cups bean sprouts",
        "1 cup broccoli florets",
        "3 tablespoons soy sauce",
        "2 tablespoons tamarind paste",
        "1 tablespoon vegetable oil",
        "1 tablespoon brown sugar",
        "Chopped peanuts for garnish",
      ],
      recipeInstructions: [
        "Cook rice noodles according to package instructions.",
        "In a pan, stir-fry tofu until golden.",
        "Add broccoli, bean sprouts, soy sauce, tamarind paste, and brown sugar.",
        "Toss in cooked noodles and mix well.",
        "Garnish with chopped peanuts.",
        "Serve hot.",
      ],
    },
    {
      dishName: "Chickpea Curry",
      type: "Indian cuisine",
      photoURL: "https://www.allrecipes.com/thmb/iO7l9FNOWP25EsmbIJB4-utQV0Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Coconut_Chickpea_Curry-4x3_039-cfa7a55e16434fba8641012f7b03cef8.jpg",
      id: 12,
      tags: ["Indian", "Vegan", "High-protein"],
      ingredients: [
        "1 can chickpeas, drained and rinsed",
        "1 onion, finely chopped",
        "2 tomatoes, pureed",
        "2 cloves garlic, minced",
        "1 tablespoon curry powder",
        "1 teaspoon cumin",
        "1 teaspoon coriander",
        "1/2 cup coconut milk",
        "Fresh cilantro for garnish",
      ],
      recipeInstructions: [
        "In a pan, sauté chopped onion until translucent.",
        "Add minced garlic and cook for 1 minute.",
        "Stir in curry powder, cumin, and coriander.",
        "Add chickpeas, tomato puree, and coconut milk. Simmer for 15 minutes.",
        "Garnish with fresh cilantro and serve with rice or naan.",
      ],
    },
    {
      dishName: "Margherita Pizza",
      type: "Italian cuisine",
      photoURL: "https://www.allrecipes.com/thmb/EWUfG5l45Y_WJX507xu2jKLYLMo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/279581margherita-flatbread-pizzalutzflcat4x3-d8e0f6bba57d478883af6433e080de03.jpeg",
      id: 13,
      tags: ["Vegetarian", "Italian", "Budget-friendly"],
      ingredients: [
        "1 pizza dough",
        "1/2 cup tomato sauce",
        "1 ball fresh mozzarella, sliced",
        "Fresh basil leaves",
        "2 tablespoons olive oil",
        "Salt and pepper to taste",
      ],
      recipeInstructions: [
        "Preheat oven to 475°F (245°C).",
        "Roll out pizza dough on a floured surface and transfer to a baking sheet.",
        "Spread tomato sauce evenly over the dough.",
        "Arrange mozzarella slices and fresh basil leaves.",
        "Drizzle with olive oil and season with salt and pepper.",
        "Bake for 12-15 minutes or until crust is golden and cheese is bubbly.",
        "Slice and serve.",
      ],
    },
    {
      dishName: "Tacos al Pastor",
      type: "Mexican cuisine",
      photoURL: "https://www.allrecipes.com/thmb/79eN3zZLzZ0GL1BOIUSZGuKKWEM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/chicken-al-pastor-ddmfs-0831-4x3-1-07333bb010104b059996d70da5c02be0.jpg",
      id: 14,
      tags: ["Mexican", "High-protein", "Halal"],
      ingredients: [
        "1 lb pork shoulder, thinly sliced",
        "3 tablespoons achiote paste",
        "1 pineapple, sliced",
        "1 onion, finely chopped",
        "2 cloves garlic, minced",
        "1 teaspoon cumin",
        "Corn tortillas",
        "Cilantro and lime for garnish",
      ],
      recipeInstructions: [
        "Marinate pork slices in achiote paste, cumin, garlic, and onion for 1 hour.",
        "Grill marinated pork until cooked through.",
        "Warm corn tortillas on the grill or in a pan.",
        "Assemble tacos with grilled pork, pineapple slices, cilantro, and a squeeze of lime.",
        "Serve immediately.",
      ],
    },
    {
      dishName: "Caprese Stuffed Portobello Mushrooms",
      type: "Mediterranean cuisine",
      photoURL: "https://cafedelites.com/wp-content/uploads/2019/12/Caprese-Stuffed-Portobellos-IMAGE-34.jpg",
      id: 15,
      tags: ["Vegetarian", "Low-carb"],
      ingredients: [
        "4 large portobello mushrooms, stems removed",
        "1 cup cherry tomatoes, halved",
        "1 ball fresh mozzarella, diced",
        "Fresh basil leaves",
        "2 tablespoons balsamic glaze",
        "Salt and pepper to taste",
      ],
      recipeInstructions: [
        "Preheat the oven to 400°F (200°C).",
        "In a bowl, mix cherry tomatoes, mozzarella, and basil.",
        "Brush portobello mushrooms with olive oil and season with salt and pepper.",
        "Fill each mushroom with the tomato-mozzarella mixture.",
        "Bake for 15-20 minutes or until mushrooms are tender.",
        "Drizzle with balsamic glaze before serving.",
      ],
    },
    {
      dishName: "Chicken Satay Skewers",
      type: "Indonesian cuisine",
      photoURL: "https://www.allrecipes.com/thmb/1fxvn6mru02isTqzKcsBGNS_Gik=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/1615395-db08c8a21f254657b82e3c3fb4217d53.jpg",
      id: 16,
      tags: ["High-protein", "Indonesian", "Halal"],
      ingredients: [
        "1 lb chicken breast, cut into strips",
        "1/4 cup soy sauce",
        "2 tablespoons peanut butter",
        "2 tablespoons honey",
        "1 tablespoon lime juice",
        "2 cloves garlic, minced",
        "Wooden skewers, soaked in water",
      ],
      recipeInstructions: [
        "In a bowl, mix soy sauce, peanut butter, honey, lime juice, and minced garlic.",
        "Marinate chicken strips in the mixture for at least 30 minutes.",
        "Thread marinated chicken onto soaked skewers.",
        "Grill or broil skewers for 8-10 minutes, turning occasionally.",
        "Serve hot with extra sauce for dipping.",
      ],
    },
    {
      dishName: "Spaghetti Bolognese",
      type: "Italian cuisine",
      photoURL: "https://www.allrecipes.com/thmb/ZQZXOErs8CI3FWLb8gH39BIbjjI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/2433171-bolognese-sauce-Allrecipes-Magazine-1x1-1-91e4bb43a13b42b6b2eddff2c82e59ec.jpg",
      id: 17,
      tags: ["Italian", "< 1 hour", "Budget-friendly"],
      ingredients: [
        "1 lb ground beef",
        "1 onion, finely chopped",
        "2 cloves garlic, minced",
        "1 can crushed tomatoes",
        "2 tablespoons tomato paste",
        "1 teaspoon dried oregano",
        "1 teaspoon dried basil",
        "Salt and pepper to taste",
        "Spaghetti noodles",
      ],
      recipeInstructions: [
        "In a pan, cook ground beef until browned. Drain excess fat.",
        "Add chopped onion and minced garlic, cook until softened.",
        "Stir in crushed tomatoes, tomato paste, oregano, and basil.",
        "Simmer for 20-30 minutes, season with salt and pepper.",
        "Cook spaghetti noodles according to package instructions.",
        "Serve Bolognese sauce over cooked spaghetti.",
      ],
    },
    {
      dishName: "Kimchi Fried Rice",
      type: "Korean cuisine",
      photoURL: "https://www.allrecipes.com/thmb/DKzlbWmZCD635ggiMeVNCIAPuvM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/1065049-a898cbecc5594f89a9c816261d740617.jpg",
      id: 18,
      tags: ["Korean", "Budget-friendly", "< 30 min"],
      ingredients: [
        "2 cups cooked rice",
        "1 cup kimchi, chopped",
        "1/2 cup tofu, diced",
        "1 carrot, finely chopped",
        "3 green onions, sliced",
        "2 tablespoons soy sauce",
        "1 tablespoon sesame oil",
        "1 teaspoon gochugaru (Korean red pepper flakes)",
        "Fried egg for topping",
      ],
      recipeInstructions: [
        "Heat sesame oil in a pan over medium heat.",
        "Add chopped kimchi, tofu, carrot, and green onions. Stir-fry for 3-5 minutes.",
        "Add cooked rice, soy sauce, and gochugaru. Mix well.",
        "Top with a fried egg and serve hot.",
      ],
    },
    {
      dishName: "Chicken Enchiladas",
      type: "Mexican cuisine",
      photoURL: "https://www.allrecipes.com/thmb/M4XsxGgwnV-YCv9qWC4-W3NZjUk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Chicken-Enchiladas-739fd129b4f3439293859ba87f263162.jpg",
      id: 19,
      tags: ["High-protein", "< 1 hour", "Mexican"],
      ingredients: [
        "2 cups shredded cooked chicken",
        "1 can black beans, drained and rinsed",
        "1 cup corn kernels",
        "1 cup shredded cheddar cheese",
        "1/2 cup diced tomatoes",
        "1/4 cup chopped cilantro",
        "1 teaspoon chili powder",
        "1/2 teaspoon cumin",
        "8 flour tortillas",
        "Enchilada sauce",
      ],
      recipeInstructions: [
        "Preheat oven to 375°F (190°C).",
        "In a bowl, mix shredded chicken, black beans, corn, tomatoes, cilantro, and spices.",
        "Divide the mixture among the tortillas, roll them up, and place them in a baking dish.",
        "Pour enchilada sauce over the rolled tortillas and top with shredded cheese.",
        "Bake for 20-25 minutes or until cheese is melted and bubbly.",
        "Serve with sour cream and additional cilantro if desired.",
      ],
    },
    {
      dishName: "General Tso's Tofu",
      type: "Chinese cuisine",
      photoURL: "https://www.allrecipes.com/thmb/uQgtU6dEzTUWUsHlOnaxbVSYOW8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/8335491-aaae724fe2864d6e981501765f74f788.jpg",
      id: 20,
      tags: ["Vegetarian", "High-protein", "Chinese"],
      ingredients: [
        "1 lb firm tofu, cubed",
        "1/4 cup soy sauce",
        "2 tablespoons rice vinegar",
        "2 tablespoons hoisin sauce",
        "1 tablespoon sesame oil",
        "1 tablespoon cornstarch",
        "2 cloves garlic, minced",
        "1 teaspoon ginger, grated",
        "1/2 cup broccoli florets",
        "1/2 cup bell peppers, sliced",
        "Cooked white rice for serving",
      ],
      recipeInstructions: [
        "In a bowl, mix soy sauce, rice vinegar, hoisin sauce, sesame oil, and cornstarch.",
        "Marinate tofu in the sauce for 15-20 minutes.",
        "In a pan, sauté garlic and ginger until fragrant.",
        "Add marinated tofu, broccoli, and bell peppers. Stir-fry until tofu is golden and veggies are tender.",
        "Serve over cooked white rice.",
      ],
    },
    {
      dishName: "Mango Lassi",
      type: "Indian cuisine",
      photoURL: "https://www.allrecipes.com/thmb/azE_2VztYuzM4bxWhvZ_3P-gWbI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/9436929-17fe10fccd994b76976d9c1de92d6678.jpg",
      id: 21,
      tags: ["Vegetarian", "Indian", "< 30 min"],
      ingredients: [
        "1 cup ripe mango, diced",
        "1 cup plain yogurt",
        "1/2 cup milk",
        "2 tablespoons honey",
        "1/4 teaspoon cardamom",
        "Ice cubes",
        "Mint leaves for garnish",
      ],
      recipeInstructions: [
        "In a blender, combine diced mango, yogurt, milk, honey, and cardamom.",
        "Blend until smooth and creamy.",
        "Add ice cubes and blend again until frothy.",
        "Pour into glasses, garnish with mint leaves, and serve chilled.",
      ],
    },
    {
      dishName: "Pasta Puttanesca",
      type: "Italian cuisine",
      photoURL: "https://www.allrecipes.com/thmb/_2WNI_9HcRn-lGGPKYixT6Mwq28=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/8108516-0f6355760ac24f4ea6e955422973bbe4.jpg",
      id: 22,
      tags: ["< 30 min", "Mediterranean"],
      ingredients: [
        "8 oz spaghetti",
        "1 can diced tomatoes",
        "1/2 cup Kalamata olives, sliced",
        "2 tablespoons capers",
        "3 cloves garlic, minced",
        "2 tablespoons olive oil",
        "1 teaspoon red pepper flakes",
        "Fresh parsley for garnish",
      ],
      recipeInstructions: [
        "Cook spaghetti according to package instructions.",
        "In a pan, sauté garlic in olive oil until fragrant.",
        "Add diced tomatoes, olives, capers, and red pepper flakes. Simmer for 10 minutes.",
        "Toss cooked spaghetti in the sauce and garnish with fresh parsley.",
        "Serve hot.",
      ],
    }
];
