export const DUMMY_DATA = [
  {
    dishName: "Fried Rice",
    type: "Chinese cuisine",
    photoURL: "https://houseofnasheats.com/wp-content/uploads/2023/01/Chicken-Fried-Rice-Recipe-12-scaled.jpg",
    id: 1,
    tags: ["Chinese", "High-protein"],
    ingredients: [
      "2 cups cooked rice",
      "1 cup diced chicken",
      "1 cup mixed vegetables (peas, carrots, corn)",
      "3 eggs, beaten",
      "4 tablespoons soy sauce",
      "1 tablespoon oil",
      "Salt and pepper to taste",
    ],
    recipeInstructions: [
      "Heat oil in a pan over medium heat.",
      "Add diced chicken and cook until browned.",
      "Push chicken to one side, add beaten eggs to the other side, and scramble.",
      "Add mixed vegetables and stir-fry for a few minutes.",
      "Add cooked rice and soy sauce, mix well.",
      "Season with salt and pepper to taste.",
      "Serve hot.",
    ],
  },
  {
    dishName: "Pesto Pasta",
    type: "Italian cuisine",
    photoURL: "https://www.cookingclassy.com/wp-content/uploads/2022/02/pesto-pasta-1.jpg",
    id: 2,
    tags: ["Vegetarian", "Italian"],
    ingredients: [
      "8 oz pasta",
      "1 cup fresh basil leaves",
      "1/2 cup grated Parmesan cheese",
      "1/2 cup pine nuts",
      "2 cloves garlic",
      "1/2 cup extra-virgin olive oil",
      "Salt and pepper to taste",
    ],
    recipeInstructions: [
      "Cook pasta according to package instructions.",
      "In a food processor, combine basil, Parmesan, pine nuts, and garlic. Pulse until finely chopped.",
      "With the processor running, slowly add olive oil until smooth.",
      "Season with salt and pepper to taste.",
      "Toss cooked pasta with pesto sauce and serve.",
    ],
  },
  {
    dishName: "Shrimp Curry",
    type: "Indonesian cuisine",
    photoURL: "https://dishingouthealth.com/wp-content/uploads/2022/08/CoconutShrimpSkillet_Styled1.jpg",
    id: 3,
    tags: ["Indonesian", "High-protein"],
    ingredients: [
      "1 lb shrimp, peeled and deveined",
      "1 can coconut milk",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 tablespoons red curry paste",
      "1 tablespoon fish sauce",
      "1 tablespoon brown sugar",
      "Fresh cilantro for garnish",
    ],
    recipeInstructions: [
      "In a pan, sautÃ© chopped onion until softened.",
      "Add red curry paste and cook for 1-2 minutes.",
      "Add shrimp and cook until pink and opaque.",
      "Stir in coconut milk, chopped tomatoes, fish sauce, and brown sugar. Simmer for 5-7 minutes.",
      "Garnish with fresh cilantro and serve over rice.",
    ],
  }
  {
        dishName: "Cheeseburger",
        type: "American cuisine",
        photoURL: "https://peppersandpennies.com/wp-content/uploads/2017/08/PP-20170814-3.jpg",
        id: 4,
        filter: "American",
        tag: "High-protein",
        ingredients: [
            "1/2 pound medium ground beef",
            "1/2 pound ground pork",
            "1/2 sleeve of saltine crackers, finely crushed",
            "1/4 cup yellow onions, finely diced",
            "1 clove garlic, crushed",
            "1 tablespoon black pepper",
            "1 teaspoon salt",
            "1 teaspoon Worcestershire sauce",
            "1 large egg",
            "Buns and topping desired",
        ],
        recipeInstructions: [
            "Cook on grill or pan to medium-high.",
            "Mix all ingredients in large mixing bowl.",
            "Divide meat mixture into 4 equal sized balls",
            "Press down to create burger patties of equal width",
            "Grill or cook burgers at 160F, flipping only once.",
            "Remove from heat and let rest as you prepare the buns",
        ],
    },
    {
        dishName: "Reuben Sandwich",
        type: "American cuisine",
        photoURL: "https://www.allrecipes.com/thmb/4NsIWzNOAdTd69ADBr6UFt6W-c8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/47717-reuben-sandwich-ii-mike-phillips-b77c676e6aaf45e280d34e0c668d8f2f.jpeg",
        id: 5,
        filter: "American",
        tag: ["Kosher", "< 1 hour"],
        ingredients: [
            "2 slices of rye bread",
            "1/2 cup Thousand Island dressing",
            "2 slices Swiss chesse",
            "2 slices deli slices corned beef",
            "1 cup sauerkraut, drained",
            "2 tablespoons butter, softened"
        ],
        recipeInstructions: [
            "Spread the dressing on one side of each slice of bread.",
            "Assemble the sandwiches. Butter the top of each sandwich.",
            "Place the sandwich butter-side down on the hot skillet or griddle.",
            "Butter the other side. Flip when the bottom slice is golden brown.",
            "Grill until both sides are golden brown.",
        ],
    },
    {
        dishName: "Hotdog",
        type: "American cuisine",
        photoURL: "https://media.cnn.com/api/v1/images/stellar/prod/170203114440-hot-dog.jpg",
        id: 6,
        filter: "American",
        tag: ["Kosher", "Budget-friendly"],
        ingredients: [
            "1 hotdog",
            "1 hotdog bun",
            "Topping of choice",
        ],
        recipeInstructions: [
            "Bring a pot of water to a simmer.",
            "Add hotdog and simmer for 5 minutes",
            "Prepare the buns to liking",
            "Place hotdog in bun.",
            "Add toppings to liking"
        ],
    },
    {
        dishName: "Bibimbap",
        type: "Korean cuisine",
        photoURL: "https://recipetineats.com/wp-content/uploads/2019/05/Bibimbap_3.jpg",
        id: 7,
        filter: "Korean",
        tag: "High-protein",
        ingredients: [
           "Cooked short-grain white rice",
           "1 cup julienned carrots" ,
           "1 cup bean sprouts",
           "1/2 pound beef",
           "2 tablespoons soy sauce",
           "1 clove garlic, minced",
           "2 tablespoons gochujang",
           "1 fried egg",
           "Sesame seeds",
        ],
        recipeInstructions: [
            "Saute carrots, spinach and zucchini.",
            "Cook beef with soy sauce and minced garlic",
            "Mix together gochujang and soy sauce",
            "Arrange rice, vegetables, and meat in a bowl",
            "Top bowl with fried egg",
            "Drizzle the gochujang sauce on top",
            "Sprinkle sesames seeds over the bibimbap",
            "Mix everything together.",
        ],
    },
];
