export const DUMMY_DATA = [
  {
    dishName: "Fried Rice",
    type: "Chinese cuisine",
    photoURL: "https://houseofnasheats.com/wp-content/uploads/2023/01/Chicken-Fried-Rice-Recipe-12-scaled.jpg",
    id: 1,
    filter: "Chinese",
    tag: "Budget-friendly",
    ingredients: [
      "2 cups cooked rice",
      "1 cup diced chicken",
      "1 cup mixed vegetables (peas, carrots, corn)",
      "3 eggs, beaten",
      "4 tablespoons soy sauce",
      "1 tablespoon oil",
      "Salt and pepper to taste",
    ],
    recipeInstructions: [
      "Heat oil in a pan over medium heat.",
      "Add diced chicken and cook until browned.",
      "Push chicken to one side, add beaten eggs to the other side, and scramble.",
      "Add mixed vegetables and stir-fry for a few minutes.",
      "Add cooked rice and soy sauce, mix well.",
      "Season with salt and pepper to taste.",
      "Serve hot.",
    ],
  },
  {
    dishName: "Pesto Pasta",
    type: "Italian cuisine",
    photoURL: "https://www.cookingclassy.com/wp-content/uploads/2022/02/pesto-pasta-1.jpg",
    id: 2,
    filter: "Italian",
    tag: ["Vegetarian", "Budget-friendly"],
    ingredients: [
      "8 oz pasta",
      "1 cup fresh basil leaves",
      "1/2 cup grated Parmesan cheese",
      "1/2 cup pine nuts",
      "2 cloves garlic",
      "1/2 cup extra-virgin olive oil",
      "Salt and pepper to taste",
    ],
    recipeInstructions: [
      "Cook pasta according to package instructions.",
      "In a food processor, combine basil, Parmesan, pine nuts, and garlic. Pulse until finely chopped.",
      "With the processor running, slowly add olive oil until smooth.",
      "Season with salt and pepper to taste.",
      "Toss cooked pasta with pesto sauce and serve.",
    ],
  },
  {
    dishName: "Shrimp Curry",
    type: "Indonesian cuisine",
    photoURL: "https://dishingouthealth.com/wp-content/uploads/2022/08/CoconutShrimpSkillet_Styled1.jpg",
    id: 3,
    filter: "Indonesian",
    tag: "High-protein",
    ingredients: [
      "1 lb shrimp, peeled and deveined",
      "1 can coconut milk",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 tablespoons red curry paste",
      "1 tablespoon fish sauce",
      "1 tablespoon brown sugar",
      "Fresh cilantro for garnish",
    ],
    recipeInstructions: [
      "In a pan, sautÃ© chopped onion until softened.",
      "Add red curry paste and cook for 1-2 minutes.",
      "Add shrimp and cook until pink and opaque.",
      "Stir in coconut milk, chopped tomatoes, fish sauce, and brown sugar. Simmer for 5-7 minutes.",
      "Garnish with fresh cilantro and serve over rice.",
    ],
  }
];
